openapi: 3.0.0
info:
  title: Recipe API
  version: 1.0.0
  description: API for managing user-created recipes with ingredients and steps

servers:
  - url: http://localhost:8080/v1

paths:
  /recipes:
    get:
      summary: Получить список рецептов
      operationId: getAllRecipes
      responses:
        '200':
          description: Список рецептов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipeDto'

    post:
      summary: Создать рецепт
      operationId: createRecipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeDto'
      responses:
        '201':
          description: Рецепт успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeDto'

  /recipes/{recipeId}:
    get:
      summary: Получить рецепт по ID
      operationId: getRecipeById
      parameters:
        - name: recipeId
          in: path
          required: true
          description: ID рецепта
          schema:
            type: integer
      responses:
        '200':
          description: Рецепт
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeDto'
        '404':
          description: Рецепт не найден
components:
  schemas:
    RecipeDto:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/IngredientDto'
        steps:
          type: array
          items:
            $ref: '#/components/schemas/StepDto'

    IngredientDto:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        quantity:
          type: string
        recipe_id:
          type: integer

    StepDto:
      type: object
      properties:
        id:
          type: integer
        description:
          type: string
        sequence:
          type: integer
        recipe_id:
          type: integer